### ISSUE TITLE
chromothripsis script

### ISSUE THREAD

**Issue by mkinnaman** [GavinHaLab/crpc-sv-pattern-study#1]
Hi!

I found your script looking for code to run shatterseek on multiple sample. Would you be able to post or share your "/scripts/join_CNsegments.R" script?

Thanks so much!

Michael

**Comment by mjko1210** [comment]
Hi Michael,

I uploaded this code to https://github.com/GavinHaLab/crpc-sv-pattern-study/blob/main/scripts/chromothripsis/join_CNsegments.R

Thanks,
Minjeong
